# Generated by Django 2.0.8 on 2018-12-06 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='started',
            new_name='starter',
        ),
    ]
